//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArasServiceObject.ESBService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/Retail/Resources/Schemas/Schema.xsd")]
    public partial class error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_codeField;
        
        private string error_detailField;
        
        private System.Xml.XmlElement error_tracyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
                this.RaisePropertyChanged("error_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error_detail {
            get {
                return this.error_detailField;
            }
            set {
                this.error_detailField = value;
                this.RaisePropertyChanged("error_detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement error_tracy {
            get {
                return this.error_tracyField;
            }
            set {
                this.error_tracyField = value;
                this.RaisePropertyChanged("error_tracy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimBtnLogoBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imageField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class SizeBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal measurementField;
        
        private string dimensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
                this.RaisePropertyChanged("Measurement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
                this.RaisePropertyChanged("Dimension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ColorBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private ColorBaseTypeDocumentURIs documentURIsField;
        
        private YearSeasonBaseType[] yearSeasonField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ColorBaseTypeDocumentURIs DocumentURIs {
            get {
                return this.documentURIsField;
            }
            set {
                this.documentURIsField = value;
                this.RaisePropertyChanged("DocumentURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YearSeason", Order=2)]
        public YearSeasonBaseType[] YearSeason {
            get {
                return this.yearSeasonField;
            }
            set {
                this.yearSeasonField = value;
                this.RaisePropertyChanged("YearSeason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ColorBaseTypeDocumentURIs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] documentURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentURI", DataType="anyURI", Order=0)]
        public string[] DocumentURI {
            get {
                return this.documentURIField;
            }
            set {
                this.documentURIField = value;
                this.RaisePropertyChanged("DocumentURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class YearSeasonBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string yearField;
        
        private SeasonEnum seasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeasonEnum Season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
                this.RaisePropertyChanged("Season");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class SeasonEnum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string seasonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeasonName {
            get {
                return this.seasonNameField;
            }
            set {
                this.seasonNameField = value;
                this.RaisePropertyChanged("SeasonName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimCategoryBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimPartHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string statusField;
        
        private TrimCategoryBaseType cateogryField;
        
        private string subCategoryField;
        
        private CustomerBaseType[] customerInfoField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TrimCategoryBaseType Cateogry {
            get {
                return this.cateogryField;
            }
            set {
                this.cateogryField = value;
                this.RaisePropertyChanged("Cateogry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubCategory {
            get {
                return this.subCategoryField;
            }
            set {
                this.subCategoryField = value;
                this.RaisePropertyChanged("SubCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerInfo", Order=4)]
        public CustomerBaseType[] CustomerInfo {
            get {
                return this.customerInfoField;
            }
            set {
                this.customerInfoField = value;
                this.RaisePropertyChanged("CustomerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class CustomerBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private string customerReferenceNumField;
        
        private string brandNameField;
        
        private string brandCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("CustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerReferenceNum {
            get {
                return this.customerReferenceNumField;
            }
            set {
                this.customerReferenceNumField = value;
                this.RaisePropertyChanged("CustomerReferenceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
                this.RaisePropertyChanged("BrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
                this.RaisePropertyChanged("BrandCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimPartBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TrimPartHeaderType trimHeaderField;
        
        private string descriptionField;
        
        private ColorBaseType[] colorField;
        
        private SizeBaseType[] sizeField;
        
        private string materialField;
        
        private string dTMField;
        
        private string idField;
        
        private TrimBtnLogoBaseType logoField;
        
        private PriceBaseType[] priceField;
        
        private YearSeasonBaseType[] yearSeasonField;
        
        private SupplierBaseType[] supplierField;
        
        private string remarksField;
        
        private URIDocumentsType sketchField;
        
        private URIDocumentsType cADField;
        
        private string[] aGPONumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TrimPartHeaderType TrimHeader {
            get {
                return this.trimHeaderField;
            }
            set {
                this.trimHeaderField = value;
                this.RaisePropertyChanged("TrimHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Color", Order=2)]
        public ColorBaseType[] Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size", Order=3)]
        public SizeBaseType[] Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DTM {
            get {
                return this.dTMField;
            }
            set {
                this.dTMField = value;
                this.RaisePropertyChanged("DTM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TrimBtnLogoBaseType Logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("Logo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Price", Order=8)]
        public PriceBaseType[] Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YearSeason", Order=9)]
        public YearSeasonBaseType[] YearSeason {
            get {
                return this.yearSeasonField;
            }
            set {
                this.yearSeasonField = value;
                this.RaisePropertyChanged("YearSeason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Order=10)]
        public SupplierBaseType[] Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
                this.RaisePropertyChanged("Supplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public URIDocumentsType Sketch {
            get {
                return this.sketchField;
            }
            set {
                this.sketchField = value;
                this.RaisePropertyChanged("Sketch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public URIDocumentsType CAD {
            get {
                return this.cADField;
            }
            set {
                this.cADField = value;
                this.RaisePropertyChanged("CAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AGPONum", Order=14)]
        public string[] AGPONum {
            get {
                return this.aGPONumField;
            }
            set {
                this.aGPONumField = value;
                this.RaisePropertyChanged("AGPONum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class PriceBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class SupplierBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierNameField;
        
        private string itemCodeField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
                this.RaisePropertyChanged("SupplierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class URIDocumentsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] documentURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentURI", DataType="anyURI", Order=0)]
        public string[] DocumentURI {
            get {
                return this.documentURIField;
            }
            set {
                this.documentURIField = value;
                this.RaisePropertyChanged("DocumentURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimBOMItemBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trimCodeField;
        
        private string trimSizeField;
        
        private int trimUsageField;
        
        private TrimBOMItemBaseTypeTrimParts trimPartsField;
        
        private ColorBaseType trimColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrimCode {
            get {
                return this.trimCodeField;
            }
            set {
                this.trimCodeField = value;
                this.RaisePropertyChanged("TrimCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrimSize {
            get {
                return this.trimSizeField;
            }
            set {
                this.trimSizeField = value;
                this.RaisePropertyChanged("TrimSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TrimUsage {
            get {
                return this.trimUsageField;
            }
            set {
                this.trimUsageField = value;
                this.RaisePropertyChanged("TrimUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TrimBOMItemBaseTypeTrimParts TrimParts {
            get {
                return this.trimPartsField;
            }
            set {
                this.trimPartsField = value;
                this.RaisePropertyChanged("TrimParts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ColorBaseType TrimColor {
            get {
                return this.trimColorField;
            }
            set {
                this.trimColorField = value;
                this.RaisePropertyChanged("TrimColor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class TrimBOMItemBaseTypeTrimParts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TrimPartBaseType[] trimPartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimPart", Order=0)]
        public TrimPartBaseType[] TrimPart {
            get {
                return this.trimPartField;
            }
            set {
                this.trimPartField = value;
                this.RaisePropertyChanged("TrimPart");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricSizeBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal measurementField;
        
        private string dimensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
                this.RaisePropertyChanged("Measurement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
                this.RaisePropertyChanged("Dimension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class GarmentShrinkageBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float lengthField;
        
        private float widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricShrinkageBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float lengthField;
        
        private float widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricComboBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comboNameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ComboName {
            get {
                return this.comboNameField;
            }
            set {
                this.comboNameField = value;
                this.RaisePropertyChanged("ComboName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricContentBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private float ratioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Ratio {
            get {
                return this.ratioField;
            }
            set {
                this.ratioField = value;
                this.RaisePropertyChanged("Ratio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricPartHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string statusField;
        
        private string cateogryField;
        
        private string wovenFabricationField;
        
        private string knitFabricationField;
        
        private CustomerBaseType[] customerInfoField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cateogry {
            get {
                return this.cateogryField;
            }
            set {
                this.cateogryField = value;
                this.RaisePropertyChanged("Cateogry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string WovenFabrication {
            get {
                return this.wovenFabricationField;
            }
            set {
                this.wovenFabricationField = value;
                this.RaisePropertyChanged("WovenFabrication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string KnitFabrication {
            get {
                return this.knitFabricationField;
            }
            set {
                this.knitFabricationField = value;
                this.RaisePropertyChanged("KnitFabrication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerInfo", Order=5)]
        public CustomerBaseType[] CustomerInfo {
            get {
                return this.customerInfoField;
            }
            set {
                this.customerInfoField = value;
                this.RaisePropertyChanged("CustomerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricPartBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] pPONumField;
        
        private FabricPartHeaderType fabricHeaderField;
        
        private SupplierBaseType[] supplierField;
        
        private string descriptionField;
        
        private string idField;
        
        private string[] yarnCountField;
        
        private FabricContentBaseType[] contentField;
        
        private string constructionField;
        
        private string dyeMethodField;
        
        private string finishingField;
        
        private string[] widthField;
        
        private string patternField;
        
        private string printingField;
        
        private string repeatVerticalField;
        
        private string repeatHorizontalField;
        
        private FabricComboBaseType colorComboField;
        
        private FabricShrinkageBaseType fabricShrinkageField;
        
        private GarmentShrinkageBaseType garmentShrinkageField;
        
        private string testingGradeField;
        
        private PriceBaseType[] priceField;
        
        private YearSeasonBaseType[] yearSeasonField;
        
        private string remarksField;
        
        private FabricSizeBaseType[] sizeField;
        
        private URIDocumentsType layoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PPONum", Order=0)]
        public string[] PPONum {
            get {
                return this.pPONumField;
            }
            set {
                this.pPONumField = value;
                this.RaisePropertyChanged("PPONum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FabricPartHeaderType FabricHeader {
            get {
                return this.fabricHeaderField;
            }
            set {
                this.fabricHeaderField = value;
                this.RaisePropertyChanged("FabricHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Order=2)]
        public SupplierBaseType[] Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
                this.RaisePropertyChanged("Supplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YarnCount", Order=5)]
        public string[] YarnCount {
            get {
                return this.yarnCountField;
            }
            set {
                this.yarnCountField = value;
                this.RaisePropertyChanged("YarnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Order=6)]
        public FabricContentBaseType[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Construction {
            get {
                return this.constructionField;
            }
            set {
                this.constructionField = value;
                this.RaisePropertyChanged("Construction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DyeMethod {
            get {
                return this.dyeMethodField;
            }
            set {
                this.dyeMethodField = value;
                this.RaisePropertyChanged("DyeMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Finishing {
            get {
                return this.finishingField;
            }
            set {
                this.finishingField = value;
                this.RaisePropertyChanged("Finishing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Width", Order=10)]
        public string[] Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
                this.RaisePropertyChanged("Pattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("Printing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RepeatVertical {
            get {
                return this.repeatVerticalField;
            }
            set {
                this.repeatVerticalField = value;
                this.RaisePropertyChanged("RepeatVertical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RepeatHorizontal {
            get {
                return this.repeatHorizontalField;
            }
            set {
                this.repeatHorizontalField = value;
                this.RaisePropertyChanged("RepeatHorizontal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public FabricComboBaseType ColorCombo {
            get {
                return this.colorComboField;
            }
            set {
                this.colorComboField = value;
                this.RaisePropertyChanged("ColorCombo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public FabricShrinkageBaseType FabricShrinkage {
            get {
                return this.fabricShrinkageField;
            }
            set {
                this.fabricShrinkageField = value;
                this.RaisePropertyChanged("FabricShrinkage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public GarmentShrinkageBaseType GarmentShrinkage {
            get {
                return this.garmentShrinkageField;
            }
            set {
                this.garmentShrinkageField = value;
                this.RaisePropertyChanged("GarmentShrinkage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TestingGrade {
            get {
                return this.testingGradeField;
            }
            set {
                this.testingGradeField = value;
                this.RaisePropertyChanged("TestingGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Price", Order=19)]
        public PriceBaseType[] Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YearSeason", Order=20)]
        public YearSeasonBaseType[] YearSeason {
            get {
                return this.yearSeasonField;
            }
            set {
                this.yearSeasonField = value;
                this.RaisePropertyChanged("YearSeason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size", Order=22)]
        public FabricSizeBaseType[] Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public URIDocumentsType Layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
                this.RaisePropertyChanged("Layout");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricBOMItemBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fabricCodeField;
        
        private string garmentComponentField;
        
        private string cutWayField;
        
        private string fabricWidthField;
        
        private string comboNameField;
        
        private float yPDField;
        
        private int pIeceFabricUsageField;
        
        private string pieceFabricSizeField;
        
        private FabricBOMItemBaseTypeFabricParts fabricPartsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FabricCode {
            get {
                return this.fabricCodeField;
            }
            set {
                this.fabricCodeField = value;
                this.RaisePropertyChanged("FabricCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GarmentComponent {
            get {
                return this.garmentComponentField;
            }
            set {
                this.garmentComponentField = value;
                this.RaisePropertyChanged("GarmentComponent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CutWay {
            get {
                return this.cutWayField;
            }
            set {
                this.cutWayField = value;
                this.RaisePropertyChanged("CutWay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FabricWidth {
            get {
                return this.fabricWidthField;
            }
            set {
                this.fabricWidthField = value;
                this.RaisePropertyChanged("FabricWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ComboName {
            get {
                return this.comboNameField;
            }
            set {
                this.comboNameField = value;
                this.RaisePropertyChanged("ComboName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float YPD {
            get {
                return this.yPDField;
            }
            set {
                this.yPDField = value;
                this.RaisePropertyChanged("YPD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PIeceFabricUsage {
            get {
                return this.pIeceFabricUsageField;
            }
            set {
                this.pIeceFabricUsageField = value;
                this.RaisePropertyChanged("PIeceFabricUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PieceFabricSize {
            get {
                return this.pieceFabricSizeField;
            }
            set {
                this.pieceFabricSizeField = value;
                this.RaisePropertyChanged("PieceFabricSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public FabricBOMItemBaseTypeFabricParts FabricParts {
            get {
                return this.fabricPartsField;
            }
            set {
                this.fabricPartsField = value;
                this.RaisePropertyChanged("FabricParts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class FabricBOMItemBaseTypeFabricParts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FabricPartBaseType[] fabricPartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FabricPart", Order=0)]
        public FabricPartBaseType[] FabricPart {
            get {
                return this.fabricPartField;
            }
            set {
                this.fabricPartField = value;
                this.RaisePropertyChanged("FabricPart");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ColorwayBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pLUField;
        
        private ColorwayBaseTypeDocumentURIs documentURIsField;
        
        private string colorwayNameField;
        
        private string customerReferenceNameField;
        
        private string customerReferenceCodeField;
        
        private YearSeasonBaseType[] yearSeasonField;
        
        private string[] bodyPatternField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PLU {
            get {
                return this.pLUField;
            }
            set {
                this.pLUField = value;
                this.RaisePropertyChanged("PLU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ColorwayBaseTypeDocumentURIs DocumentURIs {
            get {
                return this.documentURIsField;
            }
            set {
                this.documentURIsField = value;
                this.RaisePropertyChanged("DocumentURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ColorwayName {
            get {
                return this.colorwayNameField;
            }
            set {
                this.colorwayNameField = value;
                this.RaisePropertyChanged("ColorwayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerReferenceName {
            get {
                return this.customerReferenceNameField;
            }
            set {
                this.customerReferenceNameField = value;
                this.RaisePropertyChanged("CustomerReferenceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerReferenceCode {
            get {
                return this.customerReferenceCodeField;
            }
            set {
                this.customerReferenceCodeField = value;
                this.RaisePropertyChanged("CustomerReferenceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YearSeason", Order=5)]
        public YearSeasonBaseType[] YearSeason {
            get {
                return this.yearSeasonField;
            }
            set {
                this.yearSeasonField = value;
                this.RaisePropertyChanged("YearSeason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BodyPattern", Order=6)]
        public string[] BodyPattern {
            get {
                return this.bodyPatternField;
            }
            set {
                this.bodyPatternField = value;
                this.RaisePropertyChanged("BodyPattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ColorwayBaseTypeDocumentURIs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] documentURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentURI", DataType="anyURI", Order=0)]
        public string[] DocumentURI {
            get {
                return this.documentURIField;
            }
            set {
                this.documentURIField = value;
                this.RaisePropertyChanged("DocumentURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class GarmentBOMItemBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Colorway", typeof(ColorwayBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FabricBOM", typeof(FabricBOMItemBaseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ProductSizes", typeof(GarmentBOMItemBaseTypeProductSizes), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TrimBOM", typeof(TrimBOMItemBaseType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class GarmentBOMItemBaseTypeProductSizes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] productSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductSize", Order=0)]
        public string[] ProductSize {
            get {
                return this.productSizeField;
            }
            set {
                this.productSizeField = value;
                this.RaisePropertyChanged("ProductSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ProductFeaturesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string genderField;
        
        private string collectionField;
        
        private string seriesField;
        
        private string makingField;
        
        private string fitField;
        
        private string lineField;
        
        private string collarField;
        
        private string placketField;
        
        private string sleeveField;
        
        private string cuffField;
        
        private string pocketField;
        
        private string washingField;
        
        private string embroideryField;
        
        private string printingField;
        
        private string bodyPatternField;
        
        private float sAHField;
        
        private string remarksField;
        
        private YearSeasonBaseType[] yearSeasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
                this.RaisePropertyChanged("Collection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
                this.RaisePropertyChanged("Series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Making {
            get {
                return this.makingField;
            }
            set {
                this.makingField = value;
                this.RaisePropertyChanged("Making");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Fit {
            get {
                return this.fitField;
            }
            set {
                this.fitField = value;
                this.RaisePropertyChanged("Fit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Collar {
            get {
                return this.collarField;
            }
            set {
                this.collarField = value;
                this.RaisePropertyChanged("Collar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Placket {
            get {
                return this.placketField;
            }
            set {
                this.placketField = value;
                this.RaisePropertyChanged("Placket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Sleeve {
            get {
                return this.sleeveField;
            }
            set {
                this.sleeveField = value;
                this.RaisePropertyChanged("Sleeve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Cuff {
            get {
                return this.cuffField;
            }
            set {
                this.cuffField = value;
                this.RaisePropertyChanged("Cuff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Pocket {
            get {
                return this.pocketField;
            }
            set {
                this.pocketField = value;
                this.RaisePropertyChanged("Pocket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Washing {
            get {
                return this.washingField;
            }
            set {
                this.washingField = value;
                this.RaisePropertyChanged("Washing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Embroidery {
            get {
                return this.embroideryField;
            }
            set {
                this.embroideryField = value;
                this.RaisePropertyChanged("Embroidery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Printing {
            get {
                return this.printingField;
            }
            set {
                this.printingField = value;
                this.RaisePropertyChanged("Printing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BodyPattern {
            get {
                return this.bodyPatternField;
            }
            set {
                this.bodyPatternField = value;
                this.RaisePropertyChanged("BodyPattern");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public float SAH {
            get {
                return this.sAHField;
            }
            set {
                this.sAHField = value;
                this.RaisePropertyChanged("SAH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YearSeason", Order=17)]
        public YearSeasonBaseType[] YearSeason {
            get {
                return this.yearSeasonField;
            }
            set {
                this.yearSeasonField = value;
                this.RaisePropertyChanged("YearSeason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ProductBaseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductBaseTypeStyle styleField;
        
        private string yearField;
        
        private string seasonField;
        
        private CustomerBaseType[] customerInfoField;
        
        private string productTypeField;
        
        private string productCategoryField;
        
        private string productSubCategoryField;
        
        private ProductBaseTypeFinalDevelopmentSample finalDevelopmentSampleField;
        
        private ProductFeaturesType productFeaturesField;
        
        private string materialStatusField;
        
        private URIDocumentsType imageField;
        
        private URIDocumentsType paperPatternField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProductBaseTypeStyle Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
                this.RaisePropertyChanged("Style");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Season {
            get {
                return this.seasonField;
            }
            set {
                this.seasonField = value;
                this.RaisePropertyChanged("Season");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerInfo", Order=3)]
        public CustomerBaseType[] CustomerInfo {
            get {
                return this.customerInfoField;
            }
            set {
                this.customerInfoField = value;
                this.RaisePropertyChanged("CustomerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("ProductType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("ProductCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProductSubCategory {
            get {
                return this.productSubCategoryField;
            }
            set {
                this.productSubCategoryField = value;
                this.RaisePropertyChanged("ProductSubCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ProductBaseTypeFinalDevelopmentSample FinalDevelopmentSample {
            get {
                return this.finalDevelopmentSampleField;
            }
            set {
                this.finalDevelopmentSampleField = value;
                this.RaisePropertyChanged("FinalDevelopmentSample");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ProductFeaturesType ProductFeatures {
            get {
                return this.productFeaturesField;
            }
            set {
                this.productFeaturesField = value;
                this.RaisePropertyChanged("ProductFeatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MaterialStatus {
            get {
                return this.materialStatusField;
            }
            set {
                this.materialStatusField = value;
                this.RaisePropertyChanged("MaterialStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public URIDocumentsType Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public URIDocumentsType PaperPattern {
            get {
                return this.paperPatternField;
            }
            set {
                this.paperPatternField = value;
                this.RaisePropertyChanged("PaperPattern");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ProductBaseTypeStyle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string idField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esquel.com/Product/namespace/")]
    public partial class ProductBaseTypeFinalDevelopmentSample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
