//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArasServiceObject.FabricPartManageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectionFilter", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.Common")]
    [System.SerializableAttribute()]
    public partial class SelectionFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.SelectionFilter[] FiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchOperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName {
            get {
                return this.AttributeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeNameField, value) != true)) {
                    this.AttributeNameField = value;
                    this.RaisePropertyChanged("AttributeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterType {
            get {
                return this.FilterTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterTypeField, value) != true)) {
                    this.FilterTypeField = value;
                    this.RaisePropertyChanged("FilterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterValue {
            get {
                return this.FilterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterValueField, value) != true)) {
                    this.FilterValueField = value;
                    this.RaisePropertyChanged("FilterValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.SelectionFilter[] Filters {
            get {
                return this.FiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltersField, value) != true)) {
                    this.FiltersField = value;
                    this.RaisePropertyChanged("Filters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchOperator {
            get {
                return this.SearchOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchOperatorField, value) != true)) {
                    this.SearchOperatorField = value;
                    this.RaisePropertyChanged("SearchOperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricPartClass", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricPartClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayPageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayPageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricPartList FabricPartListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.eumImageType GetImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetReturnStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.SelectionFilter SelectionFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessFlagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayPageIndex {
            get {
                return this.DisplayPageIndexField;
            }
            set {
                if ((this.DisplayPageIndexField.Equals(value) != true)) {
                    this.DisplayPageIndexField = value;
                    this.RaisePropertyChanged("DisplayPageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayPageSize {
            get {
                return this.DisplayPageSizeField;
            }
            set {
                if ((this.DisplayPageSizeField.Equals(value) != true)) {
                    this.DisplayPageSizeField = value;
                    this.RaisePropertyChanged("DisplayPageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetail {
            get {
                return this.ErrorDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailField, value) != true)) {
                    this.ErrorDetailField = value;
                    this.RaisePropertyChanged("ErrorDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorString {
            get {
                return this.ErrorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorStringField, value) != true)) {
                    this.ErrorStringField = value;
                    this.RaisePropertyChanged("ErrorString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricPartList FabricPartList {
            get {
                return this.FabricPartListField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricPartListField, value) != true)) {
                    this.FabricPartListField = value;
                    this.RaisePropertyChanged("FabricPartList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.eumImageType GetImageType {
            get {
                return this.GetImageTypeField;
            }
            set {
                if ((this.GetImageTypeField.Equals(value) != true)) {
                    this.GetImageTypeField = value;
                    this.RaisePropertyChanged("GetImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetReturnString {
            get {
                return this.GetReturnStringField;
            }
            set {
                if ((object.ReferenceEquals(this.GetReturnStringField, value) != true)) {
                    this.GetReturnStringField = value;
                    this.RaisePropertyChanged("GetReturnString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationID {
            get {
                return this.OperationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIDField, value) != true)) {
                    this.OperationIDField = value;
                    this.RaisePropertyChanged("OperationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.SelectionFilter SelectionFilter {
            get {
                return this.SelectionFilterField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectionFilterField, value) != true)) {
                    this.SelectionFilterField = value;
                    this.RaisePropertyChanged("SelectionFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessFlag {
            get {
                return this.SuccessFlagField;
            }
            set {
                if ((this.SuccessFlagField.Equals(value) != true)) {
                    this.SuccessFlagField = value;
                    this.RaisePropertyChanged("SuccessFlag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricPartList", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricPartList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricPartBaseType[] FabricPartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricPartBaseType[] FabricPart {
            get {
                return this.FabricPartField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricPartField, value) != true)) {
                    this.FabricPartField = value;
                    this.RaisePropertyChanged("FabricPart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eumImageType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    public enum eumImageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsePrimaryPath = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseTempPath = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricPartBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricPartBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricComboBaseType ColorComboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstructionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricContentBaseType[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DyeMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricPartHeaderType FabricHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricShrinkageBaseType FabricShrinkageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinishingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.GarmentShrinkageBaseType GarmentShrinkageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.URIDocumentsType LayoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PPONumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatternField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.PriceBaseType[] PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepeatHorizontalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepeatVerticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.FabricSizeBaseType[] SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.SupplierBaseType[] SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestingGradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YarnCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.YearSeasonBaseType[] YearSeasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricComboBaseType ColorCombo {
            get {
                return this.ColorComboField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorComboField, value) != true)) {
                    this.ColorComboField = value;
                    this.RaisePropertyChanged("ColorCombo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Construction {
            get {
                return this.ConstructionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstructionField, value) != true)) {
                    this.ConstructionField = value;
                    this.RaisePropertyChanged("Construction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricContentBaseType[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DyeMethod {
            get {
                return this.DyeMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.DyeMethodField, value) != true)) {
                    this.DyeMethodField = value;
                    this.RaisePropertyChanged("DyeMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricPartHeaderType FabricHeader {
            get {
                return this.FabricHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricHeaderField, value) != true)) {
                    this.FabricHeaderField = value;
                    this.RaisePropertyChanged("FabricHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricShrinkageBaseType FabricShrinkage {
            get {
                return this.FabricShrinkageField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricShrinkageField, value) != true)) {
                    this.FabricShrinkageField = value;
                    this.RaisePropertyChanged("FabricShrinkage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Finishing {
            get {
                return this.FinishingField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishingField, value) != true)) {
                    this.FinishingField = value;
                    this.RaisePropertyChanged("Finishing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.GarmentShrinkageBaseType GarmentShrinkage {
            get {
                return this.GarmentShrinkageField;
            }
            set {
                if ((object.ReferenceEquals(this.GarmentShrinkageField, value) != true)) {
                    this.GarmentShrinkageField = value;
                    this.RaisePropertyChanged("GarmentShrinkage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.URIDocumentsType Layout {
            get {
                return this.LayoutField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutField, value) != true)) {
                    this.LayoutField = value;
                    this.RaisePropertyChanged("Layout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PPONum {
            get {
                return this.PPONumField;
            }
            set {
                if ((object.ReferenceEquals(this.PPONumField, value) != true)) {
                    this.PPONumField = value;
                    this.RaisePropertyChanged("PPONum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pattern {
            get {
                return this.PatternField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternField, value) != true)) {
                    this.PatternField = value;
                    this.RaisePropertyChanged("Pattern");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.PriceBaseType[] Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Printing {
            get {
                return this.PrintingField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintingField, value) != true)) {
                    this.PrintingField = value;
                    this.RaisePropertyChanged("Printing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepeatHorizontal {
            get {
                return this.RepeatHorizontalField;
            }
            set {
                if ((object.ReferenceEquals(this.RepeatHorizontalField, value) != true)) {
                    this.RepeatHorizontalField = value;
                    this.RaisePropertyChanged("RepeatHorizontal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepeatVertical {
            get {
                return this.RepeatVerticalField;
            }
            set {
                if ((object.ReferenceEquals(this.RepeatVerticalField, value) != true)) {
                    this.RepeatVerticalField = value;
                    this.RaisePropertyChanged("RepeatVertical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.FabricSizeBaseType[] Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.SupplierBaseType[] Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestingGrade {
            get {
                return this.TestingGradeField;
            }
            set {
                if ((object.ReferenceEquals(this.TestingGradeField, value) != true)) {
                    this.TestingGradeField = value;
                    this.RaisePropertyChanged("TestingGrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Width {
            get {
                return this.WidthField;
            }
            set {
                if ((object.ReferenceEquals(this.WidthField, value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YarnCount {
            get {
                return this.YarnCountField;
            }
            set {
                if ((object.ReferenceEquals(this.YarnCountField, value) != true)) {
                    this.YarnCountField = value;
                    this.RaisePropertyChanged("YarnCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.YearSeasonBaseType[] YearSeason {
            get {
                return this.YearSeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.YearSeasonField, value) != true)) {
                    this.YearSeasonField = value;
                    this.RaisePropertyChanged("YearSeason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricComboBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricComboBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComboNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComboName {
            get {
                return this.ComboNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ComboNameField, value) != true)) {
                    this.ComboNameField = value;
                    this.RaisePropertyChanged("ComboName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricPartHeaderType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricPartHeaderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CateogryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.CustomerBaseType[] CustomerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KnitFabricationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WovenFabricationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cateogry {
            get {
                return this.CateogryField;
            }
            set {
                if ((object.ReferenceEquals(this.CateogryField, value) != true)) {
                    this.CateogryField = value;
                    this.RaisePropertyChanged("Cateogry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.CustomerBaseType[] CustomerInfo {
            get {
                return this.CustomerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInfoField, value) != true)) {
                    this.CustomerInfoField = value;
                    this.RaisePropertyChanged("CustomerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KnitFabrication {
            get {
                return this.KnitFabricationField;
            }
            set {
                if ((object.ReferenceEquals(this.KnitFabricationField, value) != true)) {
                    this.KnitFabricationField = value;
                    this.RaisePropertyChanged("KnitFabrication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WovenFabrication {
            get {
                return this.WovenFabricationField;
            }
            set {
                if ((object.ReferenceEquals(this.WovenFabricationField, value) != true)) {
                    this.WovenFabricationField = value;
                    this.RaisePropertyChanged("WovenFabrication");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricShrinkageBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricShrinkageBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GarmentShrinkageBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class GarmentShrinkageBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URIDocumentsType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class URIDocumentsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DocumentURIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DocumentURI {
            get {
                return this.DocumentURIField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentURIField, value) != true)) {
                    this.DocumentURIField = value;
                    this.RaisePropertyChanged("DocumentURI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricContentBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricContentBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RatioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Ratio {
            get {
                return this.RatioField;
            }
            set {
                if ((this.RatioField.Equals(value) != true)) {
                    this.RatioField = value;
                    this.RaisePropertyChanged("Ratio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class PriceBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FabricSizeBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class FabricSizeBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MeasurementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension {
            get {
                return this.DimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionField, value) != true)) {
                    this.DimensionField = value;
                    this.RaisePropertyChanged("Dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Measurement {
            get {
                return this.MeasurementField;
            }
            set {
                if ((this.MeasurementField.Equals(value) != true)) {
                    this.MeasurementField = value;
                    this.RaisePropertyChanged("Measurement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class SupplierBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YearSeasonBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class YearSeasonBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.FabricPartManageService.SeasonEnum SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.FabricPartManageService.SeasonEnum Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonField, value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class CustomerBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerReferenceNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandCodeField, value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReferenceNum {
            get {
                return this.CustomerReferenceNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceNumField, value) != true)) {
                    this.CustomerReferenceNumField = value;
                    this.RaisePropertyChanged("CustomerReferenceNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonEnum", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class SeasonEnum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeasonNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeasonName {
            get {
                return this.SeasonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonNameField, value) != true)) {
                    this.SeasonNameField = value;
                    this.RaisePropertyChanged("SeasonName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esquel.com/ArasService/FabricPartManageService", ConfigurationName="FabricPartManageService.IFabricPartManageService")]
    public interface IFabricPartManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartList", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartListResponse")]
        ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartList(ArasServiceObject.FabricPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartList", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartListResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartListAsync(ArasServiceObject.FabricPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartByID", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartByIDResponse")]
        ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartByID(string pi_fabricPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartByID", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartByIDResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartByIDAsync(string pi_fabricPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartImage", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartImageResponse")]
        ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartImage(string pi_fabricPartID, ArasServiceObject.FabricPartManageService.eumImageType pi_getImageType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartImage", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Ge" +
            "tFabricPartImageResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartImageAsync(string pi_fabricPartID, ArasServiceObject.FabricPartManageService.eumImageType pi_getImageType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateAndFilter", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateAndFilterResponse")]
        ArasServiceObject.FabricPartManageService.SelectionFilter CreateAndFilter(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateAndFilter", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateAndFilterResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateAndFilterAsync(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateOrFilter", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateOrFilterResponse")]
        ArasServiceObject.FabricPartManageService.SelectionFilter CreateOrFilter(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateOrFilter", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateOrFilterResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateOrFilterAsync(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateLeaf", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateLeafResponse")]
        ArasServiceObject.FabricPartManageService.SelectionFilter CreateLeaf(string attributeName, string searchOperator, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateLeaf", ReplyAction="http://esquel.com/ArasService/FabricPartManageService/IFabricPartManageService/Cr" +
            "eateLeafResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateLeafAsync(string attributeName, string searchOperator, string filterValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFabricPartManageServiceChannel : ArasServiceObject.FabricPartManageService.IFabricPartManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FabricPartManageServiceClient : System.ServiceModel.ClientBase<ArasServiceObject.FabricPartManageService.IFabricPartManageService>, ArasServiceObject.FabricPartManageService.IFabricPartManageService {
        
        public FabricPartManageServiceClient() {
        }
        
        public FabricPartManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FabricPartManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricPartManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricPartManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartList(ArasServiceObject.FabricPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize) {
            return base.Channel.GetFabricPartList(pi_selectionFilter, pi_pageIndex, pi_pageSize);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartListAsync(ArasServiceObject.FabricPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize) {
            return base.Channel.GetFabricPartListAsync(pi_selectionFilter, pi_pageIndex, pi_pageSize);
        }
        
        public ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartByID(string pi_fabricPartID) {
            return base.Channel.GetFabricPartByID(pi_fabricPartID);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartByIDAsync(string pi_fabricPartID) {
            return base.Channel.GetFabricPartByIDAsync(pi_fabricPartID);
        }
        
        public ArasServiceObject.FabricPartManageService.FabricPartClass GetFabricPartImage(string pi_fabricPartID, ArasServiceObject.FabricPartManageService.eumImageType pi_getImageType) {
            return base.Channel.GetFabricPartImage(pi_fabricPartID, pi_getImageType);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.FabricPartClass> GetFabricPartImageAsync(string pi_fabricPartID, ArasServiceObject.FabricPartManageService.eumImageType pi_getImageType) {
            return base.Channel.GetFabricPartImageAsync(pi_fabricPartID, pi_getImageType);
        }
        
        public ArasServiceObject.FabricPartManageService.SelectionFilter CreateAndFilter(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateAndFilter(filters);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateAndFilterAsync(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateAndFilterAsync(filters);
        }
        
        public ArasServiceObject.FabricPartManageService.SelectionFilter CreateOrFilter(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateOrFilter(filters);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateOrFilterAsync(ArasServiceObject.FabricPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateOrFilterAsync(filters);
        }
        
        public ArasServiceObject.FabricPartManageService.SelectionFilter CreateLeaf(string attributeName, string searchOperator, string filterValue) {
            return base.Channel.CreateLeaf(attributeName, searchOperator, filterValue);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.FabricPartManageService.SelectionFilter> CreateLeafAsync(string attributeName, string searchOperator, string filterValue) {
            return base.Channel.CreateLeafAsync(attributeName, searchOperator, filterValue);
        }
    }
}
