//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArasServiceObject.TrimPartManageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectionFilter", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.Common")]
    [System.SerializableAttribute()]
    public partial class SelectionFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.SelectionFilter[] FiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchOperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName {
            get {
                return this.AttributeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeNameField, value) != true)) {
                    this.AttributeNameField = value;
                    this.RaisePropertyChanged("AttributeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterType {
            get {
                return this.FilterTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterTypeField, value) != true)) {
                    this.FilterTypeField = value;
                    this.RaisePropertyChanged("FilterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterValue {
            get {
                return this.FilterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterValueField, value) != true)) {
                    this.FilterValueField = value;
                    this.RaisePropertyChanged("FilterValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.SelectionFilter[] Filters {
            get {
                return this.FiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltersField, value) != true)) {
                    this.FiltersField = value;
                    this.RaisePropertyChanged("Filters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchOperator {
            get {
                return this.SearchOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchOperatorField, value) != true)) {
                    this.SearchOperatorField = value;
                    this.RaisePropertyChanged("SearchOperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimPartClass", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimPartClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayPageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisplayPageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.eumImageType GetImageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetReturnStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.SelectionFilter SelectionFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.TrimPartList TrimPartListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayPageIndex {
            get {
                return this.DisplayPageIndexField;
            }
            set {
                if ((this.DisplayPageIndexField.Equals(value) != true)) {
                    this.DisplayPageIndexField = value;
                    this.RaisePropertyChanged("DisplayPageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayPageSize {
            get {
                return this.DisplayPageSizeField;
            }
            set {
                if ((this.DisplayPageSizeField.Equals(value) != true)) {
                    this.DisplayPageSizeField = value;
                    this.RaisePropertyChanged("DisplayPageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetail {
            get {
                return this.ErrorDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailField, value) != true)) {
                    this.ErrorDetailField = value;
                    this.RaisePropertyChanged("ErrorDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorString {
            get {
                return this.ErrorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorStringField, value) != true)) {
                    this.ErrorStringField = value;
                    this.RaisePropertyChanged("ErrorString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.eumImageType GetImageType {
            get {
                return this.GetImageTypeField;
            }
            set {
                if ((this.GetImageTypeField.Equals(value) != true)) {
                    this.GetImageTypeField = value;
                    this.RaisePropertyChanged("GetImageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetReturnString {
            get {
                return this.GetReturnStringField;
            }
            set {
                if ((object.ReferenceEquals(this.GetReturnStringField, value) != true)) {
                    this.GetReturnStringField = value;
                    this.RaisePropertyChanged("GetReturnString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationID {
            get {
                return this.OperationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIDField, value) != true)) {
                    this.OperationIDField = value;
                    this.RaisePropertyChanged("OperationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.SelectionFilter SelectionFilter {
            get {
                return this.SelectionFilterField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectionFilterField, value) != true)) {
                    this.SelectionFilterField = value;
                    this.RaisePropertyChanged("SelectionFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessFlag {
            get {
                return this.SuccessFlagField;
            }
            set {
                if ((this.SuccessFlagField.Equals(value) != true)) {
                    this.SuccessFlagField = value;
                    this.RaisePropertyChanged("SuccessFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.TrimPartList TrimPartList {
            get {
                return this.TrimPartListField;
            }
            set {
                if ((object.ReferenceEquals(this.TrimPartListField, value) != true)) {
                    this.TrimPartListField = value;
                    this.RaisePropertyChanged("TrimPartList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimPartList", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimPartList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.TrimPartBaseType[] TrimPartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.TrimPartBaseType[] TrimPart {
            get {
                return this.TrimPartField;
            }
            set {
                if ((object.ReferenceEquals(this.TrimPartField, value) != true)) {
                    this.TrimPartField = value;
                    this.RaisePropertyChanged("TrimPart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eumImageType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    public enum eumImageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsePrimaryPath = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseTempPath = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimPartBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimPartBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AGPONumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.URIDocumentsType CADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.ColorBaseType[] ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.TrimBtnLogoBaseType LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.PriceBaseType[] PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.SizeBaseType[] SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.URIDocumentsType SketchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.SupplierBaseType[] SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.TrimPartHeaderType TrimHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.YearSeasonBaseType[] YearSeasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AGPONum {
            get {
                return this.AGPONumField;
            }
            set {
                if ((object.ReferenceEquals(this.AGPONumField, value) != true)) {
                    this.AGPONumField = value;
                    this.RaisePropertyChanged("AGPONum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.URIDocumentsType CAD {
            get {
                return this.CADField;
            }
            set {
                if ((object.ReferenceEquals(this.CADField, value) != true)) {
                    this.CADField = value;
                    this.RaisePropertyChanged("CAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.ColorBaseType[] Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTM {
            get {
                return this.DTMField;
            }
            set {
                if ((object.ReferenceEquals(this.DTMField, value) != true)) {
                    this.DTMField = value;
                    this.RaisePropertyChanged("DTM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.TrimBtnLogoBaseType Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.PriceBaseType[] Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.SizeBaseType[] Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.URIDocumentsType Sketch {
            get {
                return this.SketchField;
            }
            set {
                if ((object.ReferenceEquals(this.SketchField, value) != true)) {
                    this.SketchField = value;
                    this.RaisePropertyChanged("Sketch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.SupplierBaseType[] Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.TrimPartHeaderType TrimHeader {
            get {
                return this.TrimHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.TrimHeaderField, value) != true)) {
                    this.TrimHeaderField = value;
                    this.RaisePropertyChanged("TrimHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.YearSeasonBaseType[] YearSeason {
            get {
                return this.YearSeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.YearSeasonField, value) != true)) {
                    this.YearSeasonField = value;
                    this.RaisePropertyChanged("YearSeason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URIDocumentsType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class URIDocumentsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DocumentURIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DocumentURI {
            get {
                return this.DocumentURIField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentURIField, value) != true)) {
                    this.DocumentURIField = value;
                    this.RaisePropertyChanged("DocumentURI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimBtnLogoBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimBtnLogoBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimPartHeaderType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimPartHeaderType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.TrimCategoryBaseType CateogryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.CustomerBaseType[] CustomerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.TrimCategoryBaseType Cateogry {
            get {
                return this.CateogryField;
            }
            set {
                if ((object.ReferenceEquals(this.CateogryField, value) != true)) {
                    this.CateogryField = value;
                    this.RaisePropertyChanged("Cateogry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.CustomerBaseType[] CustomerInfo {
            get {
                return this.CustomerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInfoField, value) != true)) {
                    this.CustomerInfoField = value;
                    this.RaisePropertyChanged("CustomerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ColorBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.ColorBaseTypeDocumentURIs DocumentURIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.YearSeasonBaseType[] YearSeasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.ColorBaseTypeDocumentURIs DocumentURIs {
            get {
                return this.DocumentURIsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentURIsField, value) != true)) {
                    this.DocumentURIsField = value;
                    this.RaisePropertyChanged("DocumentURIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.YearSeasonBaseType[] YearSeason {
            get {
                return this.YearSeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.YearSeasonField, value) != true)) {
                    this.YearSeasonField = value;
                    this.RaisePropertyChanged("YearSeason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class PriceBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizeBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class SizeBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MeasurementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension {
            get {
                return this.DimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionField, value) != true)) {
                    this.DimensionField = value;
                    this.RaisePropertyChanged("Dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Measurement {
            get {
                return this.MeasurementField;
            }
            set {
                if ((this.MeasurementField.Equals(value) != true)) {
                    this.MeasurementField = value;
                    this.RaisePropertyChanged("Measurement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class SupplierBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YearSeasonBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class YearSeasonBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArasServiceObject.TrimPartManageService.SeasonEnum SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArasServiceObject.TrimPartManageService.SeasonEnum Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonField, value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorBaseTypeDocumentURIs", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ColorBaseTypeDocumentURIs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DocumentURIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DocumentURI {
            get {
                return this.DocumentURIField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentURIField, value) != true)) {
                    this.DocumentURIField = value;
                    this.RaisePropertyChanged("DocumentURI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonEnum", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class SeasonEnum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeasonNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeasonName {
            get {
                return this.SeasonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonNameField, value) != true)) {
                    this.SeasonNameField = value;
                    this.RaisePropertyChanged("SeasonName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrimCategoryBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class TrimCategoryBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBaseType", Namespace="http://schemas.datacontract.org/2004/07/ArasInnovatorService.ArasModel.PublicMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class CustomerBaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerReferenceNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandCodeField, value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReferenceNum {
            get {
                return this.CustomerReferenceNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceNumField, value) != true)) {
                    this.CustomerReferenceNumField = value;
                    this.RaisePropertyChanged("CustomerReferenceNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esquel.com/ArasService/TrimPartManageService", ConfigurationName="TrimPartManageService.ITrimPartManageService")]
    public interface ITrimPartManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartList", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartListResponse")]
        ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartList(ArasServiceObject.TrimPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartList", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartListResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartListAsync(ArasServiceObject.TrimPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartByID", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartByIDResponse")]
        ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartByID(string pi_trimPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartByID", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartByIDResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartByIDAsync(string pi_trimPartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartImage", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartImageResponse")]
        ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartImage(string pi_trimPartID, ArasServiceObject.TrimPartManageService.eumImageType pi_getImageType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartImage", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/GetTri" +
            "mPartImageResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartImageAsync(string pi_trimPartID, ArasServiceObject.TrimPartManageService.eumImageType pi_getImageType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "AndFilter", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "AndFilterResponse")]
        ArasServiceObject.TrimPartManageService.SelectionFilter CreateAndFilter(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "AndFilter", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "AndFilterResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateAndFilterAsync(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "OrFilter", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "OrFilterResponse")]
        ArasServiceObject.TrimPartManageService.SelectionFilter CreateOrFilter(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "OrFilter", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "OrFilterResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateOrFilterAsync(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "Leaf", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "LeafResponse")]
        ArasServiceObject.TrimPartManageService.SelectionFilter CreateLeaf(string attributeName, string searchOperator, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "Leaf", ReplyAction="http://esquel.com/ArasService/TrimPartManageService/ITrimPartManageService/Create" +
            "LeafResponse")]
        System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateLeafAsync(string attributeName, string searchOperator, string filterValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrimPartManageServiceChannel : ArasServiceObject.TrimPartManageService.ITrimPartManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrimPartManageServiceClient : System.ServiceModel.ClientBase<ArasServiceObject.TrimPartManageService.ITrimPartManageService>, ArasServiceObject.TrimPartManageService.ITrimPartManageService {
        
        public TrimPartManageServiceClient() {
        }
        
        public TrimPartManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrimPartManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrimPartManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrimPartManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartList(ArasServiceObject.TrimPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize) {
            return base.Channel.GetTrimPartList(pi_selectionFilter, pi_pageIndex, pi_pageSize);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartListAsync(ArasServiceObject.TrimPartManageService.SelectionFilter pi_selectionFilter, int pi_pageIndex, int pi_pageSize) {
            return base.Channel.GetTrimPartListAsync(pi_selectionFilter, pi_pageIndex, pi_pageSize);
        }
        
        public ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartByID(string pi_trimPartID) {
            return base.Channel.GetTrimPartByID(pi_trimPartID);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartByIDAsync(string pi_trimPartID) {
            return base.Channel.GetTrimPartByIDAsync(pi_trimPartID);
        }
        
        public ArasServiceObject.TrimPartManageService.TrimPartClass GetTrimPartImage(string pi_trimPartID, ArasServiceObject.TrimPartManageService.eumImageType pi_getImageType) {
            return base.Channel.GetTrimPartImage(pi_trimPartID, pi_getImageType);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.TrimPartClass> GetTrimPartImageAsync(string pi_trimPartID, ArasServiceObject.TrimPartManageService.eumImageType pi_getImageType) {
            return base.Channel.GetTrimPartImageAsync(pi_trimPartID, pi_getImageType);
        }
        
        public ArasServiceObject.TrimPartManageService.SelectionFilter CreateAndFilter(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateAndFilter(filters);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateAndFilterAsync(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateAndFilterAsync(filters);
        }
        
        public ArasServiceObject.TrimPartManageService.SelectionFilter CreateOrFilter(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateOrFilter(filters);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateOrFilterAsync(ArasServiceObject.TrimPartManageService.SelectionFilter[] filters) {
            return base.Channel.CreateOrFilterAsync(filters);
        }
        
        public ArasServiceObject.TrimPartManageService.SelectionFilter CreateLeaf(string attributeName, string searchOperator, string filterValue) {
            return base.Channel.CreateLeaf(attributeName, searchOperator, filterValue);
        }
        
        public System.Threading.Tasks.Task<ArasServiceObject.TrimPartManageService.SelectionFilter> CreateLeafAsync(string attributeName, string searchOperator, string filterValue) {
            return base.Channel.CreateLeafAsync(attributeName, searchOperator, filterValue);
        }
    }
}
